### ISSUE TITLE
Add a white background to input_comparison.drawio

### ISSUE THREAD

**Issue by ghost** [qimiko/click-on-steps#16]
It's hard to see the diagram in README while using dark mode:
![screeennenenenshot](https://github.com/user-attachments/assets/68a20d71-3d43-450c-9b4d-59159c980d22)

Adding a white background to it would solve this

That's all, great mod btw

**Comment by qimiko** [comment]
hmm, it seems to set the theme automatically for me

<img width="681" alt="image" src="https://github.com/user-attachments/assets/ee63c98b-d600-4dd6-abd3-95f0ac556f1e">

if you're using a custom theme, it might not handle that properly. but i'll check and see if setting the theme through github also enables dark mode (it should, but it could not)

**Comment by ghost** [comment]
Oops, apparently it's because of my browser? On Brave it also seems to be fine. It's very probably my browser, I'm sorry. Closing this issue now
