### ISSUE TITLE
Is TPS bypass work?

### ISSUE THREAD

**Issue by VeensCal** [qimiko/click-on-steps#4]

**Comment by qimiko** [comment]
i'm assuming you mean physics bypass? i've tested this exactly once with a physics bypass and it seemed to work. obviously, these things can be implemented in very different ways, including ways that would break this mod, so feel free to test for yourself.
if you want to use a physics bypass, i would highly recommend just using cbf instead

if you mean the tps bypass that is nowadays referred to as draw divide, then it should work, although it'd be redundant. this mod runs at a lower level than draw divide
