### ISSUE TITLE
Port this mod to 2.206

### ISSUE THREAD

**Issue by AdamElsayed101** [qimiko/click-on-steps#9]
I literally cannot play the game again without this mod.

**Comment by TheInsane101** [comment]
CBF is updated, as well as Draw Divide. Use one of those two to make the waiting process for COS easier.

**Comment by qimiko** [comment]
😖

android and macos should work if you just compile the latest version of the source. will have to test further, ofc. windows may take some time as i want to fix some mod compatibility issues first. and also i don't like doing windows stuff. lol
(thankfully, someone started the port for me, so i know i don't have to make a lot of changes)

**Comment by GaryAlex506** [comment]
So it is possible in 2.0.6 on Android or not? And if you can, how do I do it please, playing 60fpa on my cell phone is torture HAHAHA

**Comment by qimiko** [comment]
port is finished, pending a million windows mod compatibility fixes. it'll be released after i do some testing
